// <auto-generated />
using System;
using FitnessTracker.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251201235829_AddCompletedFieldsToTrainerAssignedWorkout")]
    partial class AddCompletedFieldsToTrainerAssignedWorkout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FitnessTracker.Models.TrainerAssignedWorkout", b =>
                {
                    b.Property<int>("TrainerAssignedWorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrainerAssignedWorkoutId");

                    b.HasIndex("ClientId");

                    b.HasIndex("TrainerId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("TrainerAssignedWorkouts");
                });

            modelBuilder.Entity("FitnessTracker.Models.TrainerClientRequest", b =>
                {
                    b.Property<int>("TrainerClientRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrainerClientRequestId");

                    b.HasIndex("ClientId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerClientRequests");
                });

            modelBuilder.Entity("FitnessTracker.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitnessTracker.Models.UserWorkoutTemplate", b =>
                {
                    b.Property<int>("UserWorkoutTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserWorkoutTemplateId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("UserWorkoutTemplates");
                });

            modelBuilder.Entity("FitnessTracker.Models.UserWorkoutTemplateExercise", b =>
                {
                    b.Property<int>("UserWorkoutTemplateExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserWorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("UserWorkoutTemplateExerciseId");

                    b.HasIndex("UserWorkoutTemplateId");

                    b.ToTable("UserWorkoutTemplateExercises");
                });

            modelBuilder.Entity("FitnessTracker.Models.Workout", b =>
                {
                    b.Property<int>("WorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalReps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Weight")
                        .HasColumnType("REAL");

                    b.Property<string>("WorkoutStyle")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkoutId");

                    b.HasIndex("UserId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FitnessTracker.Models.WorkoutExercise", b =>
                {
                    b.Property<int>("WorkoutExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkoutExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("FitnessTracker.Models.WorkoutSet", b =>
                {
                    b.Property<int>("WorkoutSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkoutSetId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("FitnessTracker.Models.WorkoutTemplate", b =>
                {
                    b.Property<int>("WorkoutTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkoutTemplateId");

                    b.ToTable("WorkoutTemplates");

                    b.HasData(
                        new
                        {
                            WorkoutTemplateId = 1001,
                            Category = "Biceps",
                            TemplateName = "Biceps Workout"
                        },
                        new
                        {
                            WorkoutTemplateId = 1002,
                            Category = "Triceps",
                            TemplateName = "Triceps Workout"
                        },
                        new
                        {
                            WorkoutTemplateId = 1003,
                            Category = "Back",
                            TemplateName = "Back Workout"
                        },
                        new
                        {
                            WorkoutTemplateId = 1004,
                            Category = "Legs",
                            TemplateName = "Leg Workout"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.WorkoutTemplateExercise", b =>
                {
                    b.Property<int>("WorkoutTemplateExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkoutTemplateExerciseId");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("WorkoutTemplateExercises");

                    b.HasData(
                        new
                        {
                            WorkoutTemplateExerciseId = 2001,
                            ExerciseName = "Dumbbell Bicep Curl",
                            Reps = 10,
                            Sets = 3,
                            Weight = 0.0,
                            WorkoutTemplateId = 1001
                        },
                        new
                        {
                            WorkoutTemplateExerciseId = 2002,
                            ExerciseName = "Hammer Curl",
                            Reps = 12,
                            Sets = 3,
                            Weight = 0.0,
                            WorkoutTemplateId = 1001
                        },
                        new
                        {
                            WorkoutTemplateExerciseId = 2003,
                            ExerciseName = "Tricep Cable Pushdown",
                            Reps = 12,
                            Sets = 3,
                            Weight = 0.0,
                            WorkoutTemplateId = 1002
                        },
                        new
                        {
                            WorkoutTemplateExerciseId = 2004,
                            ExerciseName = "Overhead Dumbbell Extension",
                            Reps = 10,
                            Sets = 3,
                            Weight = 0.0,
                            WorkoutTemplateId = 1002
                        },
                        new
                        {
                            WorkoutTemplateExerciseId = 2005,
                            ExerciseName = "Lat Pulldown",
                            Reps = 10,
                            Sets = 3,
                            Weight = 0.0,
                            WorkoutTemplateId = 1003
                        },
                        new
                        {
                            WorkoutTemplateExerciseId = 2006,
                            ExerciseName = "Seated Cable Row",
                            Reps = 12,
                            Sets = 3,
                            Weight = 0.0,
                            WorkoutTemplateId = 1003
                        },
                        new
                        {
                            WorkoutTemplateExerciseId = 2007,
                            ExerciseName = "Leg Press",
                            Reps = 10,
                            Sets = 3,
                            Weight = 0.0,
                            WorkoutTemplateId = 1004
                        },
                        new
                        {
                            WorkoutTemplateExerciseId = 2008,
                            ExerciseName = "Goblet Squat",
                            Reps = 12,
                            Sets = 3,
                            Weight = 0.0,
                            WorkoutTemplateId = 1004
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.TrainerAssignedWorkout", b =>
                {
                    b.HasOne("FitnessTracker.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Models.User", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Models.User", null)
                        .WithMany("AssignedWorkouts")
                        .HasForeignKey("UserId");

                    b.HasOne("FitnessTracker.Models.WorkoutTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Template");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitnessTracker.Models.TrainerClientRequest", b =>
                {
                    b.HasOne("FitnessTracker.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Models.User", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitnessTracker.Models.UserWorkoutTemplate", b =>
                {
                    b.HasOne("FitnessTracker.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Models.User", null)
                        .WithMany("SavedTemplates")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Models.UserWorkoutTemplateExercise", b =>
                {
                    b.HasOne("FitnessTracker.Models.UserWorkoutTemplate", "Template")
                        .WithMany("Exercises")
                        .HasForeignKey("UserWorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FitnessTracker.Models.Workout", b =>
                {
                    b.HasOne("FitnessTracker.Models.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Models.WorkoutExercise", b =>
                {
                    b.HasOne("FitnessTracker.Models.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FitnessTracker.Models.WorkoutSet", b =>
                {
                    b.HasOne("FitnessTracker.Models.Workout", "Workout")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FitnessTracker.Models.WorkoutTemplateExercise", b =>
                {
                    b.HasOne("FitnessTracker.Models.WorkoutTemplate", "Template")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FitnessTracker.Models.User", b =>
                {
                    b.Navigation("AssignedWorkouts");

                    b.Navigation("SavedTemplates");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("FitnessTracker.Models.UserWorkoutTemplate", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitnessTracker.Models.Workout", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("FitnessTracker.Models.WorkoutTemplate", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
